"""empty message

Revision ID: 405956520f21
Revises: 11d5e3302eb2
Create Date: 2020-12-16 12:17:44.536140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405956520f21'
down_revision = '11d5e3302eb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    op.drop_column('posts', 'body_html')
    op.drop_column('posts', 'title_html')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title_html', sa.TEXT(), nullable=True))
    op.add_column('posts', sa.Column('body_html', sa.TEXT(), nullable=True))
    op.add_column('posts', sa.Column('title', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
