"""body_html

Revision ID: 415ab62f11c1
Revises: 55b17ada6f87
Create Date: 2020-09-25 21:05:23.824423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415ab62f11c1'
down_revision = '55b17ada6f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
