"""delete title, title_html, body_html

Revision ID: 7b8b8f62d407
Revises: 7e61ead6b304
Create Date: 2020-09-26 21:02:41.344438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b8b8f62d407'
down_revision = '7e61ead6b304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title_html')
    op.drop_column('posts', 'body_html')
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.TEXT(), nullable=True))
    op.add_column('posts', sa.Column('body_html', sa.TEXT(), nullable=True))
    op.add_column('posts', sa.Column('title_html', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
