"""add title

Revision ID: 7e61ead6b304
Revises: 415ab62f11c1
Create Date: 2020-09-26 18:37:33.495500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e61ead6b304'
down_revision = '415ab62f11c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('title_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title_html')
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###
